### ISSUE TITLE
Do you think this game can be translated?

### ISSUE THREAD

**Issue by marcussacana** [K0lb3/Blue-Archive---Asset-Downloader#2]
I made fan translation for various games, but I had not so much experience around android.
First, I want ask if is possible translate the game even if require root for the phone.
Since is an online game the assets should be verified at startup, this mean we will need patch the APK
to ignore the checksum of some files.
But before of that, what file format store the game texts? Are something that can be easy edited?
As far I saw, the game looks like uses Unity with IL2CPP... that's make the things a bit hard...
And the encryption is something complex?

**Comment by K0lb3** [comment]
Translating the Japanese version is certainly possible, albeit quite annoying.

First of all, you would have to disable either the hash check of the files (this game is one of the rare few that actually does that instead of using a hash table), or intercept and adjust the file index received from the server.

Secondly, you would have to actually translate the localization files.
The localization seems to be stored in the excel files, which are just normal jsons.
So, you would have to rewrite these json files, and then reapply the various protection steps.

So overall, I would say it's not worth the trouble, as just the first step alone requires quite a lot of time.

**Comment by marcussacana** [comment]
I see, I need to think a bit to see if is worth of the work...
Thx for the info.
